### PR TITLE
103 dot action compatability

### PR DESCRIPTION
**Pull request by cubap**
Should redirect to path - ".action" and either succeed or 404 if the action does not exist.

### CODE REVIEW

**Comment by cubap** [comment]
okay @thehabes I need to go home. Take it or leave it. Tests are only "passing"

**Comment by thehabes** [comment]
Arrg it fails the Talend API test
image

The apps need to get a 201 with the object in the body.

Literally pulled down and npm start and tested, I looked at nothing.  I bet it's close.

We'll take it for today's work, we got further than we needed to.  Let's pick it up here tomorrow.

**Comment by cubap** [comment]
Okay.

This should not be using redirects because that has to roundtrip back to the browser. I will be changing these to path rewrites and responses within the router.

**Comment by cubap** [comment]
`/delete` is 404, `/delete/3` is 405. This is expected, but the rewrite doesn't honor this.

**Pull request merged**
